vim.g.mapleader = " "

local map = vim.keymap.set
local opts = { noremap = true, silent = true }
local plugin_config_dir = vim.fn.stdpath("config") .. "/lua/plugins"

local function load_module(module, label)
	local ok, mod = pcall(require, module)
	if ok then
		return mod
	end

	vim.notify(("%s is not available"):format(label or module), vim.log.levels.WARN)
end

local function with_snacks(callback)
	return function()
		local snacks = load_module("snacks", "snacks.nvim")
		if snacks then
			callback(snacks)
		end
	end
end

local function trouble_cmd(command)
	return function()
		if load_module("plugins.trouble", "trouble.nvim") then
			vim.cmd(command)
		end
	end
end

local function plugin_cmd(module, command, label)
	return function()
		if load_module(module, label) then
			vim.cmd(command)
		end
	end
end

map("n", "<C-h>", "<C-w>h", vim.tbl_extend("force", opts, { desc = "Move to left window" }))
map("n", "<C-j>", "<C-w>j", vim.tbl_extend("force", opts, { desc = "Move to lower window" }))
map("n", "<C-k>", "<C-w>k", vim.tbl_extend("force", opts, { desc = "Move to upper window" }))
map("n", "<C-l>", "<C-w>l", vim.tbl_extend("force", opts, { desc = "Move to right window" }))
map("n", "<S-h>", "<cmd>BufferLineCyclePrev<cr>", { desc = "Previous Buffer" })
map("n", "<S-l>", "<cmd>BufferLineCycleNext<cr>", { desc = "Next Buffer" })
map("n", "<leader>bp", "<cmd>BufferLineTogglePin<cr>", { desc = "Pin Buffer" })

-- Trouble 按键
map("n", "<leader>xx", trouble_cmd("Trouble diagnostics toggle"), { desc = "Diagnostics (Trouble)" })
map("n", "<leader>xX", trouble_cmd("Trouble diagnostics toggle filter.buf=0"), { desc = "Buffer Diagnostics (Trouble)" })
map("n", "<leader>cs", trouble_cmd("Trouble symbols toggle focus=false"), { desc = "Symbols (Trouble)" })
map("n", "<leader>cl", trouble_cmd("Trouble lsp toggle focus=false win.position=right"), { desc = "LSP (Trouble)" })
map("n", "<leader>cm", plugin_cmd("plugins.mason", "Mason", "mason.nvim"), { desc = "Mason" })
map("n", "<leader>xL", trouble_cmd("Trouble loclist toggle"), { desc = "Location List (Trouble)" })
map("n", "<leader>xQ", trouble_cmd("Trouble qflist toggle"), { desc = "Quickfix List (Trouble)" })

-- Top Pickers & Explorer
map("n", "<leader><space>", with_snacks(function(snacks)
	snacks.picker.smart()
end), { desc = "Smart Find Files" })
map("n", "<leader>,", with_snacks(function(snacks)
	snacks.picker.buffers()
end), { desc = "Buffers" })
map("n", "<leader>/", with_snacks(function(snacks)
	snacks.picker.grep()
end), { desc = "Grep" })
map("n", "<leader>:", with_snacks(function(snacks)
	snacks.picker.command_history()
end), { desc = "Command History" })
map("n", "<leader>e", with_snacks(function(snacks)
	snacks.explorer()
end), { desc = "File Explorer" })

-- find
map("n", "<leader>fb", with_snacks(function(snacks)
	snacks.picker.buffers()
end), { desc = "Buffers" })
map("n", "<leader>fc", with_snacks(function(snacks)
	snacks.picker.files({ cwd = vim.fn.stdpath("config") })
end), { desc = "Find Config File" })
map("n", "<leader>ff", with_snacks(function(snacks)
	snacks.picker.files()
end), { desc = "Find Files" })
map("n", "<leader>fg", with_snacks(function(snacks)
	snacks.picker.git_files()
end), { desc = "Find Git Files" })
map("n", "<leader>fp", with_snacks(function(snacks)
	snacks.picker.projects()
end), { desc = "Projects" })
map("n", "<leader>fr", with_snacks(function(snacks)
	snacks.picker.recent()
end), { desc = "Recent" })

-- git
map("n", "<leader>gb", with_snacks(function(snacks)
	snacks.picker.git_branches()
end), { desc = "Git Branches" })
map("n", "<leader>gl", with_snacks(function(snacks)
	snacks.picker.git_log()
end), { desc = "Git Log" })
map("n", "<leader>gL", with_snacks(function(snacks)
	snacks.picker.git_log_line()
end), { desc = "Git Log Line" })
map("n", "<leader>gs", with_snacks(function(snacks)
	snacks.picker.git_status()
end), { desc = "Git Status" })
map("n", "<leader>gS", with_snacks(function(snacks)
	snacks.picker.git_stash()
end), { desc = "Git Stash" })
map("n", "<leader>gd", with_snacks(function(snacks)
	snacks.picker.git_diff()
end), { desc = "Git Diff (Hunks)" })
map("n", "<leader>gf", with_snacks(function(snacks)
	snacks.picker.git_log_file()
end), { desc = "Git Log File" })

-- gh
map("n", "<leader>gi", with_snacks(function(snacks)
	snacks.picker.gh_issue()
end), { desc = "GitHub Issues (open)" })
map("n", "<leader>gI", with_snacks(function(snacks)
	snacks.picker.gh_issue({ state = "all" })
end), { desc = "GitHub Issues (all)" })
map("n", "<leader>gp", with_snacks(function(snacks)
	snacks.picker.gh_pr()
end), { desc = "GitHub Pull Requests (open)" })
map("n", "<leader>gP", with_snacks(function(snacks)
	snacks.picker.gh_pr({ state = "all" })
end), { desc = "GitHub Pull Requests (all)" })

-- Grep / search
map("n", "<leader>sb", with_snacks(function(snacks)
	snacks.picker.lines()
end), { desc = "Buffer Lines" })
map("n", "<leader>sB", with_snacks(function(snacks)
	snacks.picker.grep_buffers()
end), { desc = "Grep Open Buffers" })
map("n", "<leader>sg", with_snacks(function(snacks)
	snacks.picker.grep()
end), { desc = "Grep" })
map({ "n", "x" }, "<leader>sw", with_snacks(function(snacks)
	snacks.picker.grep_word()
end), { desc = "Visual selection or word" })

map("n", '<leader>s"', with_snacks(function(snacks)
	snacks.picker.registers()
end), { desc = "Registers" })
map("n", "<leader>s/", with_snacks(function(snacks)
	snacks.picker.search_history()
end), { desc = "Search History" })
map("n", "<leader>sa", with_snacks(function(snacks)
	snacks.picker.autocmds()
end), { desc = "Autocmds" })
map("n", "<leader>sc", with_snacks(function(snacks)
	snacks.picker.command_history()
end), { desc = "Command History" })
map("n", "<leader>sC", with_snacks(function(snacks)
	snacks.picker.commands()
end), { desc = "Commands" })
map("n", "<leader>sd", with_snacks(function(snacks)
	snacks.picker.diagnostics()
end), { desc = "Diagnostics" })
map("n", "<leader>sD", with_snacks(function(snacks)
	snacks.picker.diagnostics_buffer()
end), { desc = "Buffer Diagnostics" })
map("n", "<leader>sh", with_snacks(function(snacks)
	snacks.picker.help()
end), { desc = "Help Pages" })
map("n", "<leader>sH", with_snacks(function(snacks)
	snacks.picker.highlights()
end), { desc = "Highlights" })
map("n", "<leader>si", with_snacks(function(snacks)
	snacks.picker.icons()
end), { desc = "Icons" })
map("n", "<leader>sj", with_snacks(function(snacks)
	snacks.picker.jumps()
end), { desc = "Jumps" })
map("n", "<leader>sk", with_snacks(function(snacks)
	snacks.picker.keymaps()
end), { desc = "Keymaps" })
map("n", "<leader>sl", with_snacks(function(snacks)
	snacks.picker.loclist()
end), { desc = "Location List" })
map("n", "<leader>sm", with_snacks(function(snacks)
	snacks.picker.marks()
end), { desc = "Marks" })
map("n", "<leader>sM", with_snacks(function(snacks)
	snacks.picker.man()
end), { desc = "Man Pages" })
map("n", "<leader>sn", with_snacks(function(snacks)
	snacks.picker.notifications()
end), { desc = "Notification Picker" })
map("n", "<leader>sp", with_snacks(function(snacks)
	snacks.picker.files({ cwd = plugin_config_dir })
end), { desc = "Find Plugin Config" })
map("n", "<leader>sq", with_snacks(function(snacks)
	snacks.picker.qflist()
end), { desc = "Quickfix List" })
map("n", "<leader>sR", with_snacks(function(snacks)
	snacks.picker.resume()
end), { desc = "Resume" })
map("n", "<leader>su", with_snacks(function(snacks)
	snacks.picker.undo()
end), { desc = "Undo History" })
map("n", "<leader>uC", with_snacks(function(snacks)
	snacks.picker.colorschemes()
end), { desc = "Colorschemes" })

-- LSP
map("n", "gd", with_snacks(function(snacks)
	snacks.picker.lsp_definitions()
end), { desc = "Goto Definition" })
map("n", "gD", with_snacks(function(snacks)
	snacks.picker.lsp_declarations()
end), { desc = "Goto Declaration" })
map("n", "gr", with_snacks(function(snacks)
	snacks.picker.lsp_references()
end), { desc = "References", nowait = true })
map("n", "gI", with_snacks(function(snacks)
	snacks.picker.lsp_implementations()
end), { desc = "Goto Implementation" })
map("n", "gy", with_snacks(function(snacks)
	snacks.picker.lsp_type_definitions()
end), { desc = "Goto Type Definition" })
map("n", "gai", with_snacks(function(snacks)
	snacks.picker.lsp_incoming_calls()
end), { desc = "Calls Incoming" })
map("n", "gao", with_snacks(function(snacks)
	snacks.picker.lsp_outgoing_calls()
end), { desc = "Calls Outgoing" })
map("n", "<leader>ss", with_snacks(function(snacks)
	snacks.picker.lsp_symbols()
end), { desc = "LSP Symbols" })
map("n", "<leader>sS", with_snacks(function(snacks)
	snacks.picker.lsp_workspace_symbols()
end), { desc = "LSP Workspace Symbols" })

-- Other
map("n", "<leader>z", with_snacks(function(snacks)
	snacks.zen()
end), { desc = "Toggle Zen Mode" })
map("n", "<leader>Z", with_snacks(function(snacks)
	snacks.zen.zoom()
end), { desc = "Toggle Zoom" })
map("n", "<leader>.", with_snacks(function(snacks)
	snacks.scratch()
end), { desc = "Toggle Scratch Buffer" })
map("n", "<leader>S", with_snacks(function(snacks)
	snacks.scratch.select()
end), { desc = "Select Scratch Buffer" })
map("n", "<leader>n", with_snacks(function(snacks)
	snacks.notifier.show_history()
end), { desc = "Notification History" })
map("n", "<leader>bd", with_snacks(function(snacks)
	snacks.bufdelete()
end), { desc = "Delete Buffer" })
map("n", "<leader>cR", with_snacks(function(snacks)
	snacks.rename.rename_file()
end), { desc = "Rename File" })
map({ "n", "v" }, "<leader>gB", with_snacks(function(snacks)
	snacks.gitbrowse()
end), { desc = "Git Browse" })
map("n", "<leader>gg", with_snacks(function(snacks)
	snacks.lazygit()
end), { desc = "Lazygit" })
map("n", "<leader>un", with_snacks(function(snacks)
	snacks.notifier.hide()
end), { desc = "Dismiss All Notifications" })
map("n", "<c-/>", with_snacks(function(snacks)
	snacks.terminal()
end), { desc = "Toggle Terminal" })
map("n", "<c-_>", with_snacks(function(snacks)
	snacks.terminal()
end), { desc = "which_key_ignore" })
map({ "n", "t" }, "]]", with_snacks(function(snacks)
	snacks.words.jump(vim.v.count1)
end), { desc = "Next Reference" })
map({ "n", "t" }, "[[", with_snacks(function(snacks)
	snacks.words.jump(-vim.v.count1)
end), { desc = "Prev Reference" })

-- 打开 Neovim News
map("n", "<leader>N", with_snacks(function(snacks)
	snacks.win({
		file = vim.api.nvim_get_runtime_file("doc/news.txt", false)[1],
		width = 0.6,
		height = 0.6,
		wo = {
			spell = false,
			wrap = false,
			signcolumn = "yes",
			statuscolumn = " ",
			conceallevel = 3,
		},
	})
end), { desc = "Neovim News" })
